### ISSUE TITLE
audio player issue

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#965]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
Play any ayah, while its playing click on "play" button to another ayah and player will skip some portion of new ayah and continue reciting from the position where it was on previous ayah
 
**Expected / new behavior:**
Player should start from start for new ayah

**Comment by AhmedShab** [comment]
Salam Alaikum @naveed-ahmad, Ramadan Kareen, hope you're having a blessed month 😄.

I'll look into this issue. I've also noticed that sometimes when you click on any ayah, it the player shows it's loading for some reason

![image](https://user-images.githubusercontent.com/12079101/40215786-4cbccc5c-5a6b-11e8-962e-febcb94b6312.png)

**Comment by AhmedShab** [comment]
Before I start working on this I have to ask, the current master branch has an issue with the player (other then what you mentioned). When I press the play button, it throws an error right away.

![image](https://user-images.githubusercontent.com/12079101/40275697-31d8517c-5c00-11e8-9488-6d98e0109dce.png)

@naveed-ahmad Any ideas?

**Comment by naveed-ahmad** [comment]
WaAlakim o salam brother @AhmedShab, audio player has multiple issues. And these issues are holding back production build. 

https://github.com/quran/quran.com-frontend/issues/965#issuecomment-390457133 and many other isseus in audio player are due to `currentVerse` in verses container.

**Comment by AhmedShab** [comment]
Thank you @naveed-ahmad, I'll look into these issues. It might take a while but will do what I can 👍

**Comment by SuperDzej** [comment]
Not sure how you track these audio player issues, but I have seen a couple so far tested it on few surahs.

1. Can not play pass 10 ayah in surah Bakarah, also surah Ali Imran after some verses it doesn't play anymore, no errors in the developer console.
2. Surah Fatiha stops on ayah number 4 and to get to ayah number 5 need to click on play button manually, from 1 to 4 it plays automatically and after 5 it also plays automatically.
3. Surah Bakarah after first ayah second ayah goes to the last word and then skips to the third ayah. If I manually click on the second it goes from the beginning.
Probably many more things like this.

Do you have some way of keeping track of this and who is working on what, what can I do to try to help?

**Comment by AhmedShab** [comment]
Thank you @SuperDzej, I'll look into the mine issue in the codebase. It might be something that causes all these issues to happen. Inshallah, I'll find it and it will fix them all. As I work on this, I might ask for your help or something to test things out for me. Thanks again, I appreciate it

**Comment by AhmedShab** [comment]
Salam @naveed-ahmad, how are you doing?

Is there someone I could talk to who wrote the code for this? 

I basically was debugging it. I followed the actions (from redux) but having troubling finding the place here it throws that error (in the code). I've never come across `undefined in connectAdvaned.js `
```
connectAdvanced.js:226 Uncaught TypeError: Cannot read property 'verseKey' of undefined
    at Function.mapStateToProps [as mapToProps] (index.js:661)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at handleNewPropsAndNewState (selectorFactory.js:34)
    at handleSubsequentCalls (selectorFactory.js:67)
    at pureFinalPropsSelector (selectorFactory.js:74)
    at Object.runComponentSelector [as run] (connectAdvanced.js:165)
    at ProxyComponent.componentWillReceiveProps (connectAdvanced.js:127)
    at ProxyComponent.componentWillReceiveProps (createPrototypeProxy.js:44)
    at ReactCompositeComponent.js:611
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
```

I would appreciate if I could talk to someone who had a similar error from `connectAdvanced`.js

**Comment by AhmedShab** [comment]
@naveed-ahmad don't worry about it. After few hours of debugging, I found what was the issue. I think I fixed it.

@SuperDzej, do you wanna test it for me? I think it works now but sometimes when you manually change ayah, it doesn't play but doesn't throw any errors.

**Comment by SuperDzej** [comment]
@AhmedShab Sure, where did you deploy it, so I can test?

**Comment by AhmedShab** [comment]
@SuperDzej, here you go:
http://staging.quran.com:32809/

**Comment by SuperDzej** [comment]
Can not hit that port, it says not found, I have tested on http://staging.quran.com surah Fatiha looks ok now, but Bakarah and other issues are still persistent, can not play pass surah 10 etc.

**Comment by AhmedShab** [comment]
That's because I had to redeploy it. That link (http://staging.quran.com) doesn't have my work.

This is the new link with my work: http://staging.quran.com:32810/

**Comment by SuperDzej** [comment]
Ok now I can go beyond ayah 10 in surah Bakarah but only when I go with next button from the first ayah inside audio player, I can not click on play beside ayah and trigger it to play that ayah, so it is possible to go beyond ayah 10 but with next button in audio player not with play icon that every ayah has.

**Comment by AhmedShab** [comment]
Thanks. Yeah, that's the only part left. I can't see what is causing it yet. I'll try to do that next time

**Comment by fahad-ibrar** [comment]
Asalam O Alaikum Brother!
There is another issue in the player. While playing the recitation the word being recited is not highlighted. There is a difference between the time at which word highlighted and recited. The recitation is quicker than the highlighted part.

**Comment by AhmedShab** [comment]
Walaikum Salam @fahad-ibrar, 
Thank you for pointing that out. I think that how it was when I got the latest update (from the development version). Would you mind creating an issue for that? Thank you

**Comment by AhmedShab** [comment]
It should be another ticket. That's what I meant, thank you again. I appreciate it 😄

**Comment by AhmedShab** [comment]
@SuperDzej , would you mind creating an issue for what you found out? That should be another job as well. Thank you
